language: node_js
node_js:
  - 6.11
addons:
  apt:
    sources:
      - debian-sid
    packages:
      - ffmpeg
      - libcairo2-dev 
      - libjpeg-dev 
      - libpango1.0-dev 
      - libgif-dev 
      - build-essential 
      - g++
install: npm install
sudo: false
script:
  - npm test
after_success: npm run coverage
