port: 4000
hostname: localhost
uploader: false
logLevel: INFO
library: /home/svandecappelle/mu2
ostype: windows,
audio: [mp3,  wav, wma, ogg, flac]
video: [mp4, webm, flv, ogv]
defaultLanguage: fr
database: redis
redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 2
secret: eba16c61-18db-471a-9406-6371d7e42f63
bcrypt_rounds: 12
gravatar: true
local: false
requireLogin: false
allowUpload: true
allowRegisteration: 0
theme:
  base-color: rgb(45, 182, 230)
